set(PIXAURA_JPEG_SOURCES
    packages/core/vendor/codecs/jpeg/src/jcapimin.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcapistd-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcapistd-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcapistd-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jccoefct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jccoefct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jccolor-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jccolor-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jccolor-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcdctmgr-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcdctmgr-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcdiffct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcdiffct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcdiffct-16.c
    packages/core/vendor/codecs/jpeg/src/jchuff.c
    packages/core/vendor/codecs/jpeg/src/jcicc.c
    packages/core/vendor/codecs/jpeg/src/jcinit.c
    packages/core/vendor/codecs/jpeg/src/jclhuff.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jclossls-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jclossls-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jclossls-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcmainct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcmainct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcmainct-16.c
    packages/core/vendor/codecs/jpeg/src/jcmarker.c
    packages/core/vendor/codecs/jpeg/src/jcmaster.c
    packages/core/vendor/codecs/jpeg/src/jcomapi.c
    packages/core/vendor/codecs/jpeg/src/jcparam.c
    packages/core/vendor/codecs/jpeg/src/jcphuff.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcprepct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcprepct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcprepct-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcsample-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcsample-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jcsample-16.c
    packages/core/vendor/codecs/jpeg/src/jctrans.c
    packages/core/vendor/codecs/jpeg/src/jdapimin.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdapistd-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdapistd-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdapistd-16.c
    packages/core/vendor/codecs/jpeg/src/jdatadst.c
    packages/core/vendor/codecs/jpeg/src/jdatasrc.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdcoefct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdcoefct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdcolor-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdcolor-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdcolor-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jddctmgr-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jddctmgr-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jddiffct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jddiffct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jddiffct-16.c
    packages/core/vendor/codecs/jpeg/src/jdhuff.c
    packages/core/vendor/codecs/jpeg/src/jdicc.c
    packages/core/vendor/codecs/jpeg/src/jdinput.c
    packages/core/vendor/codecs/jpeg/src/jdlhuff.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdlossls-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdlossls-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdlossls-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdmainct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdmainct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdmainct-16.c
    packages/core/vendor/codecs/jpeg/src/jdmarker.c
    packages/core/vendor/codecs/jpeg/src/jdmaster.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdmerge-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdmerge-12.c
    packages/core/vendor/codecs/jpeg/src/jdphuff.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdpostct-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdpostct-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdpostct-16.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdsample-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdsample-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jdsample-16.c
    packages/core/vendor/codecs/jpeg/src/jdtrans.c
    packages/core/vendor/codecs/jpeg/src/jerror.c
    packages/core/vendor/codecs/jpeg/src/jfdctflt.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jfdctfst-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jfdctfst-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jfdctint-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jfdctint-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctflt-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctflt-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctfst-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctfst-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctint-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctint-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctred-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jidctred-12.c
    packages/core/vendor/codecs/jpeg/src/jmemmgr.c
    packages/core/vendor/codecs/jpeg/src/jpeg_nbits.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jquant1-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jquant1-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jquant2-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jquant2-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jutils-8.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jutils-12.c
    packages/core/vendor/codecs/jpeg/src/wrapper/jutils-16.c
)
set(PIXAURA_PNG_SOURCES
    packages/core/vendor/codecs/png/png.c
    packages/core/vendor/codecs/png/pngerror.c
    packages/core/vendor/codecs/png/pngget.c
    packages/core/vendor/codecs/png/pngmem.c
    packages/core/vendor/codecs/png/pngpread.c
    packages/core/vendor/codecs/png/pngread.c
    packages/core/vendor/codecs/png/pngrio.c
    packages/core/vendor/codecs/png/pngrtran.c
    packages/core/vendor/codecs/png/pngrutil.c
    packages/core/vendor/codecs/png/pngset.c
    packages/core/vendor/codecs/png/pngtrans.c
)
set(PIXAURA_ZLIB_SOURCES
    packages/core/vendor/codecs/zlib/adler32.c
    packages/core/vendor/codecs/zlib/crc32.c
    packages/core/vendor/codecs/zlib/inflate.c
    packages/core/vendor/codecs/zlib/inffast.c
    packages/core/vendor/codecs/zlib/inftrees.c
    packages/core/vendor/codecs/zlib/zutil.c
)
