file(READ "${CMAKE_CURRENT_SOURCE_DIR}/packages/core/vendor/codecs/provenance.json" codec_pins)
foreach(codec jpeg png zlib)
    string(JSON count LENGTH "${codec_pins}" ${codec} files)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
        string(JSON name MEMBER "${codec_pins}" ${codec} files ${index})
        string(JSON expected GET "${codec_pins}" ${codec} files "${name}")
        file(SHA256 "${CMAKE_CURRENT_SOURCE_DIR}/packages/core/vendor/codecs/${codec}/${name}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "Pinned ${codec} source integrity failure: ${name}")
        endif()
    endforeach()
endforeach()
