#!/usr/bin/env python3
"""Development-only exact-rational oracle; never imports/calls the CPU engine."""
from fractions import Fraction as F
from pathlib import Path
import struct,json,sys
ROOT=Path(__file__).resolve().parents[1]
def bits(v): return struct.unpack('<I',struct.pack('<f',float(v)))[0]
def val(b): return struct.unpack('<f',struct.pack('<I',b))[0]
def packed(p): return [bits(c) for q in p for c in q]
def evaluate(p,w,h,op):
 t,n=op
 if t=='crop':
  nw=(w+1)//2;return [p[(y*w+x)*4+c] for y in range(h) for x in range(nw) for c in range(4)],nw,h
 if t=='rotate':
  return [p[((h-1-x)*w+y)*4+c] for y in range(w) for x in range(h) for c in range(4)],h,w
 if not n:return list(p),w,h
 if t=='exposure':return [bits(F(val(c))*2) if i%4!=3 else c for i,c in enumerate(p)],w,h
 if t=='brightness':return [bits(F(val(c))+F(n,1000)*F(val(p[i-i%4+3]))) if i%4!=3 else c for i,c in enumerate(p)],w,h
 out=[];a=F(n,1000)
 for y in range(h):
  for x in range(w):
   center=[F(val(p[(y*w+x)*4+c])) for c in range(4)]
   if t=='sharpen' and not center[3]:out.extend(p[(y*w+x)*4:(y*w+x+1)*4]);continue
   g=[F(0)]*4
   for dy,wy in [(-1,1),(0,2),(1,1)]:
    for dx,wx in [(-1,1),(0,2),(1,1)]:
     at=(max(0,min(h-1,y+dy))*w+max(0,min(w-1,x+dx)))*4
     for c in range(4):g[c]+=F(val(p[at+c]))*wx*wy/16
   if t=='blur':q=[(1-a)*center[c]+a*g[c] for c in range(4)]
   else:q=[center[c]+a*(center[c]-center[3]*g[c]/g[3]) for c in range(3)]+[center[3]]
   b=[bits(c) for c in q]
   if t=='blur' and not val(b[3]):b[:3]=[0]*3
   out.extend(b)
 return out,w,h
def command(ops):
 params={'blur':'milli_strength','sharpen':'milli_amount','exposure':'milli_ev','brightness':'milli_linear','rotate':'quarter_turns'}
 result=[]
 for i,(tool,n) in enumerate(ops):
  p={'x_ppm':0,'y_ppm':0,'width_ppm':500000,'height_ppm':1000000} if tool=='crop' else {params[tool]:1000 if tool=='exposure' else n}
  result.append(dict(id=f'{i+1:032x}',type='pixaura.'+tool,operation_version=1,parameter_version=1,parameters=p))
 return json.dumps(dict(operations=result),sort_keys=True,separators=(',',':'))
images=[]
def image(w,h,p):images.append((w,h,packed(p)))
for color in [(0,0,0,0),(.25,.5,.75,1),(.125,.25,.375,.5),(1,0,0,1),(0,1,1,1),(-.5,2,4,1)]:image(3,3,[color]*9)
for at in (0,4,8):
 for alpha in (1,.5):image(3,3,[(alpha,alpha/2,0,alpha) if i==at else (0,0,0,0) for i in range(9)])
image(3,3,[(i%2,i%2,i%2,1) for i in range(9)])
image(3,3,[(float(i%3>0),0,float(i%3==0),1) for i in range(9)])
image(3,3,[(i/16,i/16,i/16,1) for i in range(9)])
image(3,3,[(a,0,a/2,a) for a in (0,.25,1,.5,0,.25,1,.5,0)])
image(1,1,[(.125,.25,.375,.5)])
image(1,5,[(i/8,0,.25,1) for i in range(5)])
image(5,1,[(i/8,0,.25,1) for i in range(5)])
image(3,3,[(val(1),0,0,val(1)) if i==4 else (0,0,0,0) for i in range(9)])
for at in (0,4,8):image(3,3,[(1,.5,0,1) if i==at else (0,0,0,1) for i in range(9)])
image(1,1,[(-0.0,0,-0.0,-0.0)])
image(129,3,[(1,0,0,1) if i==128 else (0,0,0,1) for i in range(387)])
cases=[]
for w,h,p in images:
 for tool in ('blur','sharpen'):
  for amount in (0,1,500,999,1000):cases.append((w,h,p,[(tool,amount)]))
ordered=[[('blur',1000),('sharpen',1000)],[('sharpen',1000),('blur',1000)],[('exposure',1000),('sharpen',700)],[('sharpen',700),('exposure',1000)],[('crop',0),('blur',1000)],[('rotate',1),('sharpen',1000)],[('brightness',300),('blur',500),('sharpen',1000)],[('blur',1000),('blur',1000)],[('sharpen',1000),('sharpen',1000)],[('blur',500),('sharpen',0),('sharpen',1000),('blur',0)]]
for w,h,p in (images[13],images[15],images[17]):
 for ops in ordered:cases.append((w,h,p,ops))
text=['// Generated by independent exact-rational detail-reference.py.','struct DetailFixture{const char* request;unsigned w,h,ow,oh;const unsigned* input;const unsigned* expected;};']
entries=[]
for i,(w,h,p,ops) in enumerate(cases):
 q=list(p);ow,oh=w,h
 for op in ops:q,ow,oh=evaluate(q,ow,oh,op)
 def array(name,a):text.append('static const unsigned '+name+'[]={'+','.join(f'0x{b:08x}' for b in a)+'};')
 array(f'detail_input_{i}',p);array(f'detail_expected_{i}',q)
 entries.append('{R"json('+command(ops)+')json",'+f'{w},{h},{ow},{oh},detail_input_{i},detail_expected_{i}'+'}')
text.append('static const DetailFixture detail_fixtures[]={'+',\n'.join(entries)+'};\n')
target=ROOT/'packages/core/tests/detail_fixtures.hpp';result='\n'.join(text)
if '--check' in sys.argv:
 if not target.exists() or target.read_text()!=result:raise SystemExit('Detail fixture mismatch')
else:target.write_text(result)
print(f'Independent exact-rational detail corpus PASS {len(cases)} fixtures')
