file(READ "${INPUT}" shader HEX)
string(LENGTH "${shader}" hex_length)
math(EXPR remainder "${hex_length} % 8")
if(NOT remainder EQUAL 0)
    message(FATAL_ERROR "SPIR-V length must be word aligned")
endif()
set(output "// Generated from repository-owned exposure.comp; do not commit.\n#include <cstdint>\nstatic constexpr uint32_t exposure_spirv[]={\n")
math(EXPR last "${hex_length}-8")
foreach(offset RANGE 0 ${last} 8)
    string(SUBSTRING "${shader}" ${offset} 8 word)
    string(SUBSTRING "${word}" 0 2 a)
    string(SUBSTRING "${word}" 2 2 b)
    string(SUBSTRING "${word}" 4 2 c)
    string(SUBSTRING "${word}" 6 2 d)
    string(APPEND output "0x${d}${c}${b}${a}u,\n")
endforeach()
string(APPEND output "};\n")
file(WRITE "${OUTPUT}" "${output}")
